/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'paulsideleau' at '4/13/15 3:32 PM' with Gradle 2.3
 *
 * @author paulsideleau, @date 4/13/15 3:32 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
