/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'paulsideleau' at '4/13/15 3:32 PM' with Gradle 2.3
 *
 * @author paulsideleau, @date 4/13/15 3:32 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
